version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - gocyclo
    - misspell
    - nakedret
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 35
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unparam
        path: "_test\\.go$"
    paths:
      - third_party$
      - builtin$
      - examples$
